<?php
$value = array (
  'navcomment' => 'N',
  'navpredict' => 'N',
  'navpartner' => 'N',
  'navseconds' => 'Y',
  'navgoods' => 'N',
  'navforum' => 'N',
  'displayfailure' => 'N',
  'teamask' => 'N',
  'creditseconds' => 'N',
  'smssubscribe' => 'N',
  'trsimple' => 'N',
  'moneysave' => 'N',
  'teamwhole' => 'N',
  'encodeid' => 'N',
  'userprivacy' => 'N',
  'usercredit' => 'Y',
  'mycoupon' => 'N',
  'cateteam' => 'Y',
  'catepartner' => 'N',
  'citypartner' => 'N',
  'cateseconds' => 'N',
  'categoods' => 'N',
  'emailverify' => 'N',
  'needmobile' => 'N',
  'mobilecode' => 'N',
);
?>